export type CustomInputType =
	| 'text'
	| 'obs'
	| 'bool'
	| 'value'
	| 'number'
	| 'email'
	| 'phone'
	| 'supplier'
	| 'client'
	| 'company'
	| 'date'
	| 'building'
	| 'cnpj'
	| 'transactionType'
	| 'incomeTransactionType'
	| 'expenseTransactionType';
