<script lang="ts">
	import type { ApexOptions } from 'apexcharts';
	import { Chart } from '@flowbite-svelte-plugins/chart';
	import { Card, A, Button, Dropdown, DropdownItem, Popover } from 'flowbite-svelte';
	import {
		ChevronDownOutline,
		ChevronRightOutline,
		PenSolid,
		DownloadSolid,
		ShareNodesSolid,
		TrashBinSolid,
		DotsHorizontalOutline
	} from 'flowbite-svelte-icons';

	export let transactionData;
	export let isExpenseChart;

	const filteredTransactionsTypes = transactionData.referenceData.transactionTypeId.filter(
		(tr: any) => tr.isExpense === isExpenseChart
	);

	const filteredTransactionRows = transactionData.rows.filter((tr: any) =>
		filteredTransactionsTypes.some((type: any) => type.id === tr.transactionTypeId)
	);

	const totalValue = filteredTransactionRows.reduce((acc: number, ftr: any) => {
		const value = Number(ftr.value);
		return acc + (isNaN(value) ? 0 : value);
	}, 0);

	const valuesList = filteredTransactionRows.reduce((acc: Record<number, number>, ftr: any) => {
		const value = Number(ftr.value);
		const typeId = ftr.transactionTypeId;
		if (isNaN(value)) return acc;
		acc[typeId] = (acc[typeId] ?? 0) + value;
		return acc;
	}, {});

	const percentageList = filteredTransactionsTypes.map((type: any) => {
		if (isNaN(valuesList[type.id])) return 0;
		else {
			const DECIMALS = 4
			const factor = 10 ** DECIMALS
			const rawValue = valuesList[type.id] / totalValue;
			return Math.round((rawValue + Number.EPSILON) * factor) / factor;
		}
	});

	const options: ApexOptions = {
		series: percentageList,
		colors: ['#245193', '#61B035', '#CD2122', '#EB7B00', ' #FCC61E', '#31A3EB', '#8D11D6'],
		chart: {
			height: '',
			width: 400,
			type: 'pie',
			background: 'transparent'
		},
		stroke: {
			colors: ['transparent']
		},
		plotOptions: {
			pie: {
				dataLabels: {
					offset: -25
				}
			}
		},
		labels: filteredTransactionsTypes.map((ftr: any) => ftr.name),
		dataLabels: {
			enabled: true,
			formatter: function (val: number) {
				return val.toFixed(1) + '%';
			},
			style: {
				fontFamily: 'Inter, sans-serif',
				fontSize: '18px'
			}
		},
		legend: {
			position: 'right',
			fontFamily: 'Inter, sans-serif',
			fontSize: '14px',
			labels: {
				colors: '#ffffff'
			}
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			},
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		}
	};
</script>

<Card class="border-transparent bg-transparent px-4 pt-0 pb-4 dark:bg-transparent">
	<div class="flex w-full items-start justify-between">
		<div class="flex-col items-center">
			<div class="mb-1 flex items-center">
				<Popover
					class="z-10 w-72 rounded-lg border  bg-transparent text-sm text-gray-500 shadow-xs  dark:text-gray-400"
				>
					<div class="space-y-2 p-3">
						<h3 class="font-semibold text-gray-900 dark:text-white">
							Activity growth - Incremental
						</h3>
						<p>
							Report helps navigate cumulative growth of community activities. Ideally, the chart
							should have a growing trend, as stagnating chart signifies a significant decrease of
							community activity.
						</p>
						<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
						<p>
							For each date bucket, the all-time volume of activities is calculated. This means that
							activities in period n contain all activities up to period n, plus the activities
							generated by your community in period.
						</p>
						<A href="/">Read more <ChevronRightOutline class="ms-1.5 h-2 w-2" /></A>
					</div>
				</Popover>
			</div>
		</div>
		<div class="flex items-center justify-end">
			<DotsHorizontalOutline id="dots-menu" class="dots-menu dark:text-white" />
			<Dropdown simple triggeredBy="#dots-menu" class="w-44" offset={-6}>
				<DropdownItem><PenSolid class="me-2 inline h-3 w-3" /> Edit widget</DropdownItem>
				<DropdownItem><DownloadSolid class="me-2 inline h-3 w-3" />Dropdown data</DropdownItem>
				<DropdownItem><ShareNodesSolid class="me-2 inline h-3 w-3" />Add to repository</DropdownItem
				>
				<DropdownItem><TrashBinSolid class="me-2 inline h-3 w-3" />Delete widget</DropdownItem>
			</Dropdown>
		</div>
	</div>

	<Chart {options} class="" />

	<div class="margin flex items-center justify-end">
		<div class="relative flex items-center justify-between">
			<Button
				class="inline-flex items-center bg-transparent p-2 text-center text-base font-medium text-white hover:bg-transparent focus:ring-transparent dark:bg-transparent dark:focus:ring-transparent"
				>Últimos 6 meses<ChevronDownOutline class="m-2.5 ms-1.5 w-2.5" /></Button
			>
			<Dropdown simple class="w-40 py-2" offset={-6}>
				<DropdownItem class="z-1000 text-base text-black hover:bg-gray-200 hover:text-black"
					>Últimos 6 meses</DropdownItem
				>
				<DropdownItem class="z-1000 text-base text-black hover:bg-gray-200 hover:text-black"
					>Último ano</DropdownItem
				>
				<DropdownItem class="z-1000 text-base text-black hover:bg-gray-200 hover:text-black"
					>Sempre</DropdownItem
				>
			</Dropdown>
		</div>
	</div>
</Card>

<style>
	:global(.apexcharts-canvas .apexcharts-legend-text) {
		color: #ffffff !important;
	}

	.margin {
		margin-top: -10%;
		margin-right: 1%;
	}
</style>
