<script lang="ts">
	import type { ApexOptions } from 'apexcharts';
	import { Chart } from '@flowbite-svelte-plugins/chart';
	import { Card, A, Button, Dropdown, DropdownItem, Popover } from 'flowbite-svelte';
	import {
		ChevronDownOutline,
		ChevronRightOutline,
		PenSolid,
		DownloadSolid,
		ShareNodesSolid,
		TrashBinSolid,
		DotsHorizontalOutline
	} from 'flowbite-svelte-icons';

	const options: ApexOptions = {
		series: [52.8, 26.8, 20.4],
		colors: ['#1C64F2', '#16BDCA', '#9061F9'],
		chart: {
			height: '',
			width: 400,
			type: 'pie',
			background: 'transparent'
		},
		stroke: {
			colors: ['transparent']
		},
		plotOptions: {
			pie: {
				dataLabels: {
					offset: -25
				}
			}
		},
		labels: ['Direct', 'Organic search', 'Referrals'],
		dataLabels: {
			enabled: true,
			style: {
				fontFamily: 'Inter, sans-serif',
			}
		},
		legend: {
			position: 'right',
			fontFamily: 'Inter, sans-serif',
      labels: {
        colors: "#ffffff",
      }
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			},
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		}
	};
</script>

<Card class="border-transparent bg-transparent px-4 pt-0 pb-4 dark:bg-transparent">
	<div class="flex w-full items-start justify-between">
		<div class="flex-col items-center">
			<div class="mb-1 flex items-center">
				<Popover
					class="z-10 w-72 rounded-lg border  bg-transparent text-sm text-gray-500 shadow-xs  dark:text-gray-400"
				>
					<div class="space-y-2 p-3">
						<h3 class="font-semibold text-gray-900 dark:text-white">
							Activity growth - Incremental
						</h3>
						<p>
							Report helps navigate cumulative growth of community activities. Ideally, the chart
							should have a growing trend, as stagnating chart signifies a significant decrease of
							community activity.
						</p>
						<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
						<p>
							For each date bucket, the all-time volume of activities is calculated. This means that
							activities in period n contain all activities up to period n, plus the activities
							generated by your community in period.
						</p>
						<A href="/">Read more <ChevronRightOutline class="ms-1.5 h-2 w-2" /></A>
					</div>
				</Popover>
			</div>
		</div>
		<div class="flex items-center justify-end">
			<DotsHorizontalOutline id="dots-menu" class="dots-menu dark:text-white" />
			<Dropdown simple triggeredBy="#dots-menu" class="w-44" offset={-6}>
				<DropdownItem><PenSolid class="me-2 inline h-3 w-3" /> Edit widget</DropdownItem>
				<DropdownItem><DownloadSolid class="me-2 inline h-3 w-3" />Dropdown data</DropdownItem>
				<DropdownItem><ShareNodesSolid class="me-2 inline h-3 w-3" />Add to repository</DropdownItem
				>
				<DropdownItem><TrashBinSolid class="me-2 inline h-3 w-3" />Delete widget</DropdownItem>
			</Dropdown>
		</div>
	</div>

	<Chart {options} class="pb-6" />

	<div class="grid grid-cols-1 items-center justify-between">
		<div class="flex items-center justify-between pt-5">
			<Button
				class="inline-flex items-center bg-transparent py-0 text-center text-sm font-medium text-white hover:bg-transparent focus:ring-transparent dark:bg-transparent dark:focus:ring-transparent"
				>Last 7 days<ChevronDownOutline class="m-2.5 ms-1.5 w-2.5" /></Button
			>
			<Dropdown simple class="w-40" offset={-6}>
				<DropdownItem>Yesterday</DropdownItem>
				<DropdownItem>Today</DropdownItem>
				<DropdownItem>Last 7 days</DropdownItem>
				<DropdownItem>Last 30 days</DropdownItem>
				<DropdownItem>Last 90 days</DropdownItem>
			</Dropdown>
		</div>
	</div>
</Card>

<style>
  :global(.apexcharts-canvas .apexcharts-legend-text) {
    color: #ffffff !important;
  }
</style>
